language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - LARAVEL=5.1
  - LARAVEL=5.2
  - LARAVEL=5.3
  - LARAVEL=dev-master

matrix:
  allow_failures:
    - env: LARAVEL=dev-master
  exclude:
    - php: 5.5
      env: LARAVEL=5.3
    - php: 5.5
      env: LARAVEL=dev-master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php -n -d extension=json.so composer.phar global require hirak/prestissimo --update-no-dev
  - php -n -d extension=json.so composer.phar require "illuminate/support" $LARAVEL -vvv
  - php -n -d extension=json.so composer.phar install --dev

script: phpunit

notifications:
  email: false
